export const FormDirectionRow = true;

// cardName, cardNumber, cardMMYYYY, cardCvc

export const FieldsUserForm = [
  {
    variant: 'outlined', // standard || outlined || filled
    id: 1,
    nameField: 'nameUser',
    label: 'checkout-form-user-name',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-user-name-error',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'outlined',
    id: 2,
    nameField: 'email',
    label: 'checkout-form-user-email',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-user-email-error',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'outlined',
    id: 3,
    nameField: 'cpf',
    label: 'checkout-form-user-cpf',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-user-cpf-error',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'outlined',
    id: 4,
    nameField: 'phone',
    label: 'checkout-form-user-phone',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-user-phone-error',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'outlined',
    id: 5,
    nameField: 'password',
    label: 'checkout-form-user-password',
    type: 'password',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-user-password-error',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'outlined',
    id: 6,
    nameField: 'passwordConfirm',
    label: 'checkout-form-user-password-confirm',
    type: 'password',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-user-password-confirm-error',
    maxLength: '',
    width: '33.3%',
  },
];

export const FieldsAdress = [
  {
    variant: 'outlined',
    id: 1,
    nameField: 'zipcode',
    label: 'checkout-form-adress-zipcode',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-adress-zipcode-error',
    maxLength: '',
    width: '25%',
  },
  {
    variant: 'outlined',
    id: 2,
    nameField: 'address',
    label: 'checkout-form-adress-street',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-adress-street-error',
    maxLength: '',
    width: '60%',
  },
  {
    variant: 'outlined',
    id: 3,
    nameField: 'numberAddress',
    label: 'checkout-form-adress-number',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-adress-number-error',
    maxLength: 7,
    width: '15%',
  },
  {
    variant: 'outlined',
    id: 4,
    nameField: 'complement',
    label: 'checkout-form-adress-complement',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-adress-complement-error',
    maxLength: 20,
    width: '25%',
  },
  {
    variant: 'outlined',
    id: 5,
    nameField: 'neighborhood',
    label: 'checkout-form-adress-neighborhood',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-adress-neighborhood-error',
    maxLength: '',
    width: '25%',
  },
  {
    variant: 'outlined',
    id: 6,
    nameField: 'city',
    label: 'checkout-form-adress-city',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-adress-city-error',
    maxLength: '',
    width: '25%',
  },
  {
    variant: 'outlined',
    id: 7,
    nameField: 'state',
    label: 'checkout-form-adress-state',
    type: 'select',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-adress-state-error',
    maxLength: '',
    width: '25%',
  },
];

export const FieldsPayment = [
  {
    variant: 'outlined',
    id: 1,
    nameField: 'name',
    label: 'checkout-form-card-name',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-card-name-error',
    maxLength: '',
    width: '50%',
  },
  {
    variant: 'outlined',
    id: 2,
    nameField: 'number',
    label: 'checkout-form-card-number',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-card-number-error',
    maxLength: '',
    width: '50%',
  },
  {
    variant: 'outlined',
    id: 3,
    nameField: 'expiry',
    label: 'checkout-form-card-expiry',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-card-expiry-error',
    maxLength: '',
    width: '50%',
  },
  {
    variant: 'outlined',
    id: 4,
    nameField: 'cvc',
    label: 'checkout-form-card-cvc',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'checkout-form-card-cvc-error',
    maxLength: 3,
    width: '50%',
  },
];
