export const FormDirectionRow = true;

// nomeCartao, numeroCartao, mesValCartao, cvvCartao

export const FieldsUserForm = [
  {
    variant: 'standard', // standard || outlined || filled
    id: 1,
    nameField: 'name',
    label: 'Name',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid name.',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'standard',
    id: 2,
    nameField: 'email',
    label: 'E-mail',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid e-mail.',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'standard',
    id: 3,
    nameField: 'cpf',
    label: 'CPF',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid cpf.',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'standard',
    id: 4,
    nameField: 'phone',
    label: 'Phone',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid phone.',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'standard',
    id: 5,
    nameField: 'password',
    label: 'Password',
    type: 'password',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Password must be at least 1 letter and 1 number',
    maxLength: '',
    width: '33.3%',
  },
  {
    variant: 'standard',
    id: 6,
    nameField: 'passwordConfirm',
    label: 'Password confirm',
    type: 'password',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Passwords are not supported',
    maxLength: '',
    width: '33.3%',
  },
];

export const FieldsAdress = [
  {
    variant: 'standard',
    id: 1,
    nameField: 'zipcode',
    label: 'Zip Code',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid zip code.',
    maxLength: '',
    width: '25%',
  },
  {
    variant: 'standard',
    id: 2,
    nameField: 'address',
    label: 'Address',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid address.',
    maxLength: '',
    width: '60%',
  },
  {
    variant: 'standard',
    id: 3,
    nameField: 'number',
    label: 'Number',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid number.',
    maxLength: 7,
    width: '15%',
  },
  {
    variant: 'standard',
    id: 4,
    nameField: 'complement',
    label: 'Complement',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid complement.',
    maxLength: 20,
    width: '25%',
  },
  {
    variant: 'standard',
    id: 5,
    nameField: 'neighborhood',
    label: 'Neighborhood',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid neighborhood.',
    maxLength: '',
    width: '25%',
  },
  {
    variant: 'standard',
    id: 6,
    nameField: 'city',
    label: 'City',
    type: 'text',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid city.',
    maxLength: '',
    width: '25%',
  },
  {
    variant: 'standard',
    id: 7,
    nameField: 'state',
    label: 'State',
    type: 'select',
    icon: 'fa fa-user',
    placeholder: '',
    msgError: 'Enter a valid state.',
    maxLength: '',
    width: '25%',
  },
];
